PSPSDK: debug/gdb-userlib.c File Reference
gdb-userlib.c File Reference
#include <pspkernel.h>
#include <pspdebug.h>
#include <string.h>
Functions
void putDebugChar (char ch)
char getDebugChar (void)
void sceKernelDcacheWBinvAll (void)
void sceKernelIcacheClearAll (void)
int _gdbSupportLibReadByte (unsigned char *address, unsigned char *dest)
int _gdbSupportLibWriteByte (char val, unsigned char *dest)
void _gdbSupportLibFlushCaches (void)
int _gdbSupportLibInit (void)
Variables
int g_initialised = 0
Function Documentation
_gdbSupportLibFlushCaches()
void _gdbSupportLibFlushCaches (void)
References NULL, pspKernelSetKernelPC, sceIoDevctl(), sceKernelDcacheWBinvAll(), and sceKernelIcacheClearAll().
_gdbSupportLibInit()
int _gdbSupportLibInit (void)
References g_initialised, sceIoAddDrv(), and sceIoDelDrv().
Referenced by pspDebugGdbStubInit().
_gdbSupportLibReadByte()
int _gdbSupportLibReadByte (unsigned char * address, unsigned char * dest)
_gdbSupportLibWriteByte()
int _gdbSupportLibWriteByte (char val, unsigned char * dest)
getDebugChar()
char getDebugChar (void)
References pspDebugSioGetchar(), and sceIoRead().
putDebugChar()
void putDebugChar (char ch)
References pspDebugSioPutchar(), and sceIoWrite().
sceKernelDcacheWBinvAll()
void sceKernelDcacheWBinvAll (void)
sceKernelIcacheClearAll()
void sceKernelIcacheClearAll (void)
Variable Documentation
g_initialised
int g_initialised = 0
Referenced by _gdbSupportLibInit(), pspDebugInstallStderrHandler(), pspDebugInstallStdinHandler(), and pspDebugInstallStdoutHandler().