PSPSDK: sdk/loadmodule.c File Reference
loadmodule.c File Reference
#include <string.h>
#include <stdio.h>
#include <pspuser.h>
Macros
#define MAX_ARGS 2048
Functions
SceUID pspSdkLoadStartModuleWithArgs (const char *filename, int mpid, int argc, char *const argv[])
Load a module and start it with arguments.
SceUID pspSdkLoadStartModule (const char *filename, int mpid)
Load a module and start it.
Macro Definition Documentation
MAX_ARGS
#define MAX_ARGS 2048
Function Documentation
pspSdkLoadStartModule()
SceUID pspSdkLoadStartModule (const char * filename, int mpid)
Load a module and start it.
Parameters
filename - Path to the module.
mpid - Memory parition ID to use to load the module int.
Returns
- The UID of the module on success, otherwise one of PspKernelErrorCodes.
References NULL, and pspSdkLoadStartModuleWithArgs().
pspSdkLoadStartModuleWithArgs()
SceUID pspSdkLoadStartModuleWithArgs (const char * filename, int mpid, int argc, char *const argv[])
Load a module and start it with arguments.
Parameters
filename - Path to the module.
mpid - Memory parition ID to use to load the module int.
argc - Number of arguments to pass to start module
argv - Array of arguments
Returns
- The UID of the module on success, otherwise one of PspKernelErrorCodes.
References SceKernelLMOption::access, i, MAX_ARGS, memset(), modid, SceKernelLMOption::mpiddata, SceKernelLMOption::mpidtext, NULL, SceKernelLMOption::position, sceKernelLoadModule(), sceKernelStartModule(), SceKernelLMOption::size, snprintf(), strcpy(), and strlen().
Referenced by pspSdkLoadStartModule().