PSPSDK: kernel/psploadcore.h File Reference
psploadcore.h File Reference
#include <pspkerneltypes.h>
Data Structures
struct SceModule
Describes a module.
struct SceLibraryEntryTable
Defines a library and its exported functions and variables.
struct SceLibraryStubTable
Specifies a library and a set of imports from that library.
Typedefs
typedef struct SceLibraryEntryTable SceLibraryEntryTable
Defines a library and its exported functions and variables.
typedef struct SceLibraryStubTable SceLibraryStubTable
Specifies a library and a set of imports from that library.
Functions
struct SceModule __attribute__ ((packed)) SceModule
Describes a module.
SceModule * sceKernelFindModuleByName (const char *modname)
Find a module by it's name.
SceModule * sceKernelFindModuleByAddress (unsigned int addr)
Find a module from an address.
SceModule * sceKernelFindModuleByUID (SceUID modid)
Find a module by it's UID.
int sceKernelModuleCount (void)
Return the count of loaded modules.
void sceKernelIcacheClearAll (void)
Invalidate the CPU's instruction cache.
Variables
struct SceModule * next
unsigned short attribute
unsigned char version [2]
char modname [27]
char terminal
unsigned int unknown1
unsigned int unknown2
SceUID modid
unsigned int unknown3 [4]
void * ent_top
unsigned int ent_size
void * stub_top
unsigned int stub_size
unsigned int unknown4 [4]
unsigned int entry_addr
unsigned int gp_value
unsigned int text_addr
unsigned int text_size
unsigned int data_size
unsigned int bss_size
unsigned int nsegment
unsigned int segmentaddr [4]
unsigned int segmentsize [4]
Typedef Documentation
SceLibraryEntryTable
typedef struct SceLibraryEntryTable SceLibraryEntryTable
Defines a library and its exported functions and variables.
Use the len member to determine the real size of the table (size = len * 4).
SceLibraryStubTable
typedef struct SceLibraryStubTable SceLibraryStubTable
Specifies a library and a set of imports from that library.
Use the len member to determine the real size of the table (size = len * 4).
Function Documentation
__attribute__()
struct SceModule __attribute__ ((packed))
Describes a module.
This structure could change in future firmware revisions.
sceKernelFindModuleByAddress()
SceModule* sceKernelFindModuleByAddress (unsigned int addr)
Find a module from an address.
Parameters
addr - Address somewhere within the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
sceKernelFindModuleByName()
SceModule* sceKernelFindModuleByName (const char * modname)
Find a module by it's name.
Parameters
modname - The name of the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
sceKernelFindModuleByUID()
SceModule* sceKernelFindModuleByUID (SceUID modid)
Find a module by it's UID.
Parameters
modid - The UID of the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
Referenced by pspSdkFixupImports(), and pspSdkQueryModuleInfoV1().
sceKernelIcacheClearAll()
void sceKernelIcacheClearAll (void)
Invalidate the CPU's instruction cache.
sceKernelModuleCount()
int sceKernelModuleCount (void)
Return the count of loaded modules.
Returns
The count of loaded modules.
Referenced by pspSdkGetModuleIdList().
Variable Documentation
attribute
unsigned short attribute
Referenced by _start().
bss_size
unsigned int bss_size
data_size
unsigned int data_size
ent_size
unsigned int ent_size
ent_top
void* ent_top
entry_addr
unsigned int entry_addr
gp_value
unsigned int gp_value
modid
SceUID modid
Referenced by pspSdkLoadStartModuleWithArgs().
modname
char modname[27]
next
struct SceModule* next
nsegment
unsigned int nsegment
segmentaddr
unsigned int segmentaddr[4]
segmentsize
unsigned int segmentsize[4]
stub_size
unsigned int stub_size
stub_top
void* stub_top
terminal
char terminal
text_addr
unsigned int text_addr
text_size
unsigned int text_size
unknown1
unsigned int unknown1
unknown2
unsigned int unknown2
unknown3
unsigned int unknown3[4]
unknown4
unsigned int unknown4[4]
version
unsigned char version[2]