PSPSDK: gu/sceGuStart.c File Reference
sceGuStart.c File Reference
#include "guInternal.h"
#include <pspkernel.h>
#include <pspge.h>
Functions
void sceGuStart (int cid, void *list)
Start filling a new display-context.
Function Documentation
sceGuStart()
void sceGuStart (int cid, void * list)
Start filling a new display-context.
Contexts available are:
GU_DIRECT - Rendering is performed as list is filled
GU_CALL - List is setup to be called from the main list
GU_SEND - List is buffered for a later call to sceGuSendList()
The previous context-type is stored so that it can be restored at sceGuFinish().
Parameters
cid - Context Type
list - Pointer to display-list (16 byte aligned)
References GuDisplayList::current, f, GuDrawBuffer::frame_buffer, GuDrawBuffer::frame_width, GuSettings::ge_callback_id, ge_list_executed, GU_AMBIENT, gu_contexts, gu_curr_context, GU_DIFFUSE, gu_draw_buffer, gu_init, gu_list, gu_settings, GU_SPECULAR, GuContext::list, GuDisplayList::parent_context, sceGeListEnQueue(), sceGuColorMaterial(), sceGuPatchDivide(), sceGuSetDither(), sceGuSpecular(), sceGuTexScale(), sendCommandi(), GuSettings::signal_offset, and GuDisplayList::start.